#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Removing NGINX configuration..."
ynh_config_remove_nginx
ynh_safe_rm "$cgit_web_root"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
